### PR TITLE
Extend make

### PR DESCRIPTION
**Pull request by fschlueter**
This is useful on a make to read binary files while not compiling the radiant code (which needs linux libraries).

@cozzyd I am an absolute beginner with make files, so please do not hesitate to comment

### CODE REVIEW

**Comment by cozzyd** [comment]
yes this is a good idea! 

Rather than listing them individually, I would probably define a rule for $(BUILD_DIR)/test/rno-g-% with different linker flags from $(BUILD)DIR) build/test/% (the more specific rule will get picked up) and then have the dump target depend on the rno-g-X targets. Then we can keep the naming convention that all binaries that start with rno-g do not depend on libradiant etc. 

Let me know if you want to take a stab at that or if I should do it.  

Also, as an aside, calling a compiled program a script is a little funny :).

**Comment by cozzyd** [comment]
I went ahead and updated and then merged this.

I also changed the names of the make targets, now they're `daq-test-progs` and `rno-g-utils`

**Comment by fschlueter** [comment]
Hey @cozzyd thanks!
Can you explain me a bit what you did (so I learn a bit Makefile)? What is `| $(BUILD_DIR)` for? And why including `$(INCLUDE)` in the dependencies is that necessary when librno-g.so is already in there?

**Comment by fschlueter** [comment]
hm I had to remove the pipe in the make file

**Pull request merged**
